version: '2'

services:

    mongodb:
        container_name: mongodb_ogc-features
        hostname: mongodb
        image: mongo:4.2
        entrypoint: [ "/usr/bin/mongod", "--dbpath", "/data", "--journal", "--bind_ip", "0.0.0.0"]
        ports:
            - "27017:27017"
        networks:
            - ogc-features

networks:
    ogc-features:
